[package]
name = "rfractalizer"
version = "0.1.0"
authors = ["Lucas Werkmeister <mail@lucaswerkmeister.de>"]

[dependencies.gtk]
git = "https://github.com/rust-gnome/gtk.git"
features = ["gtk_3_14"]

[dependencies.gdk]
git = "https://github.com/rust-gnome/gdk"
features = ["gdk_3_14"]
